services:
  app:
    container_name: backend
    build: ./app
    ports:
      - 3001:3001
    volumes:
      - ./app:/app
    depends_on:
      - database
    env_file:
      - project.env

  database:
    container_name: aurinkolab-database
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - project.env

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"  
    volumes:
      - ./frontend:/app
      - /app/node_modules 

volumes:
  postgres_data:
