name: Docker test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v4
    - name: running docker compose up --build
      run: docker-compose -f "docker-compose.test.yml" up -d --build

    - uses: actions/checkout@v4
    - name: running e2e test selenium
      run: docker compose run frontend npm run selenium-test
    
    - uses: actions/checkout@v4
    - name: running the unit test frontend
      run: docker compose run frontend npm run test

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.test.yml" down
   
